name: Deploy to GitHub Pages

on:
  deployment:
  workflow_dispatch:

jobs:
  deploy:
    name: Make PDF of syllabus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm

      - name: Build PDF
        run: npx docs-to-pdf docusaurus --initialDocURLs="https://it1081c.github.io/syllabus/" --outputPDFFilename syllabus.pdf

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: syllabus.pdf
          path: syllabus.pdf
          if-no-files-found: error
